# Form implementation generated from reading ui file 'fitsettings.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fitparbox(object):
    def setupUi(self, fitparbox):
        fitparbox.setObjectName("fitparbox")
        fitparbox.resize(340, 269)
        self.gridLayout_2 = QtWidgets.QGridLayout(fitparbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(parent=fitparbox)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 3)
        self.plotcutvalue = QtWidgets.QDoubleSpinBox(parent=fitparbox)
        self.plotcutvalue.setSingleStep(0.01)
        self.plotcutvalue.setObjectName("plotcutvalue")
        self.gridLayout_2.addWidget(self.plotcutvalue, 7, 1, 1, 2)
        self.convovcutvalue = QtWidgets.QDoubleSpinBox(parent=fitparbox)
        self.convovcutvalue.setSingleStep(0.01)
        self.convovcutvalue.setObjectName("convovcutvalue")
        self.gridLayout_2.addWidget(self.convovcutvalue, 5, 1, 1, 2)
        self.plotcutlabel = QtWidgets.QLabel(parent=fitparbox)
        self.plotcutlabel.setObjectName("plotcutlabel")
        self.gridLayout_2.addWidget(self.plotcutlabel, 7, 0, 1, 1)
        self.convovcutlabel = QtWidgets.QLabel(parent=fitparbox)
        self.convovcutlabel.setObjectName("convovcutlabel")
        self.gridLayout_2.addWidget(self.convovcutlabel, 5, 0, 1, 1)
        self.repfitvalue = QtWidgets.QSpinBox(parent=fitparbox)
        self.repfitvalue.setMaximum(10)
        self.repfitvalue.setObjectName("repfitvalue")
        self.gridLayout_2.addWidget(self.repfitvalue, 0, 1, 1, 2)
        self.contwavecutvalue = QtWidgets.QDoubleSpinBox(parent=fitparbox)
        self.contwavecutvalue.setSingleStep(0.01)
        self.contwavecutvalue.setObjectName("contwavecutvalue")
        self.gridLayout_2.addWidget(self.contwavecutvalue, 4, 1, 1, 2)
        self.okcancelbutton = QtWidgets.QDialogButtonBox(parent=fitparbox)
        self.okcancelbutton.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.okcancelbutton.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.okcancelbutton.setObjectName("okcancelbutton")
        self.gridLayout_2.addWidget(self.okcancelbutton, 8, 0, 1, 3)
        self.abundcutvalue = QtWidgets.QDoubleSpinBox(parent=fitparbox)
        self.abundcutvalue.setSingleStep(0.01)
        self.abundcutvalue.setObjectName("abundcutvalue")
        self.gridLayout_2.addWidget(self.abundcutvalue, 6, 1, 1, 2)
        self.repfitlabel = QtWidgets.QLabel(parent=fitparbox)
        self.repfitlabel.setObjectName("repfitlabel")
        self.gridLayout_2.addWidget(self.repfitlabel, 0, 0, 1, 1)
        self.contwavecutlabel = QtWidgets.QLabel(parent=fitparbox)
        self.contwavecutlabel.setObjectName("contwavecutlabel")
        self.gridLayout_2.addWidget(self.contwavecutlabel, 4, 0, 1, 1)
        self.abundcutlabel = QtWidgets.QLabel(parent=fitparbox)
        self.abundcutlabel.setObjectName("abundcutlabel")
        self.gridLayout_2.addWidget(self.abundcutlabel, 6, 0, 1, 1)
        self.cutvaltitle = QtWidgets.QLabel(parent=fitparbox)
        self.cutvaltitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cutvaltitle.setObjectName("cutvaltitle")
        self.gridLayout_2.addWidget(self.cutvaltitle, 3, 0, 1, 3)

        self.retranslateUi(fitparbox)
        self.okcancelbutton.accepted.connect(fitparbox.accept) # type: ignore
        self.okcancelbutton.rejected.connect(fitparbox.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(fitparbox)

    def retranslateUi(self, fitparbox):
        _translate = QtCore.QCoreApplication.translate
        fitparbox.setWindowTitle(_translate("fitparbox", "Fit Settings"))
        self.plotcutlabel.setText(_translate("fitparbox", "Plot"))
        self.convovcutlabel.setToolTip(_translate("fitparbox", "Can not be higher than the value of Continuum/Wave. Shift."))
        self.convovcutlabel.setText(_translate("fitparbox", "Convolution"))
        self.repfitlabel.setToolTip(_translate("fitparbox", "The number of times that it will try to fit each line. The subsequent iteration uses the previous result as start point. Default is 2."))
        self.repfitlabel.setText(_translate("fitparbox", "Forced Loop Interations"))
        self.contwavecutlabel.setText(_translate("fitparbox", "Continuum/Wave. Shift"))
        self.abundcutlabel.setText(_translate("fitparbox", "Abundance"))
        self.cutvaltitle.setToolTip(_translate("fitparbox", "The range that the fit will be applied. The value represents the full range (half of the value left to the fitted line and half to the right)."))
        self.cutvaltitle.setText(_translate("fitparbox", "Interaction range (Angstrom) for each fit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fitparbox = QtWidgets.QDialog()
    ui = Ui_fitparbox()
    ui.setupUi(fitparbox)
    fitparbox.show()
    sys.exit(app.exec())
